### PR TITLE
Added moments and tests

### PR DESCRIPTION
**Pull request by JENScoding**
added moments and test for NET; parameters nu and tau have to be respecified. If nu*tau <= 3 the variance goes to infinity. So either nu or tau has to be larger in the default setting.

### CODE REVIEW

**Comment by JENScoding** [comment]
The variance of the empirical SHASHo differs to the theoretical one by about 0.06-0.3

**Comment by JENScoding** [comment]
For any reason, rSEP3 has been skipped in the R-documentation.

**Comment by JENScoding** [comment]
Notes to ST2:
1. Please check the ifelse() statement in the mean and variance function. I am not sure if the else value = NaN. 
2. The default for tau is 2, which conflicts with the variance function. tau needs to be respecified (tau needs to be greater than 4, only then the first 4 moments can be calculated)

**Comment by JENScoding** [comment]
The message of the last commit should be: "Added moments and test for ST4",
The test failed for this distribution as nu is set to 1 by default. nu needs to be respecified otherwise the first moments do not exist.

**Comment by JENScoding** [comment]
For ST5 the default for tau needs to be respecified. If tau = 1 only the first moment exists.

**Comment by JENScoding** [comment]
The test for PARETO2 failed, because for sigma = 0.5 the variance goes to infinity. The default for sigma needs to be respecified. The test for PARETO20 failed as well, because the default for sigma needs to be respecified.

**Comment by JENScoding** [comment]
The default for Tau or sigma needs to be respecified for the GB2 distribution. If tau <= 2/sigma the variance goes to Inf

**Comment by JENScoding** [comment]
The default for mu needs to be respecified in the ZIPF distribution. For mu <= 2 the variance goes to Inf.

**Comment by JENScoding** [comment]
For the ZAZIPF the default for mu needs to be respecified. If mu <= 2 the variance goes to Inf.

**Comment by Stan125** [comment]
> Notes to ST2:
> 
> 1. Please check the ifelse() statement in the mean and variance function. I am not sure if the else value = NaN.
> 2. The default for tau is 2, which conflicts with the variance function. tau needs to be respecified (tau needs to be greater than 4, only then the first 4 moments can be calculated)

Der Check passt, aber mach ihn früher. Wenn nämlich tau < 1 oder < 2 ist, dann soll `EZ` im besten Fall garnicht erst berechnet werden. Ich hab das jetzt abgeändert, der commit kommt heute im Laufe des Tages

**Pull request merged**
